# Generated by Django 4.2.4 on 2023-09-21 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_commentmodel_post_likemodel_dislikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='dislikemodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis_like', to='authapp.postuser'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='authapp.postuser'),
        ),
        migrations.AlterUniqueTogether(
            name='dislikemodel',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='likemodel',
            unique_together={('user', 'post')},
        ),
    ]
