# Generated by Django 4.2.4 on 2023-09-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_merge_20230919_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikemodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis_like', to='authapp.postuser'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='authapp.postuser'),
        ),
        migrations.AlterUniqueTogether(
            name='dislikemodel',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='likemodel',
            unique_together={('user', 'post')},
        ),
    ]
