# Generated by Django 4.2.4 on 2023-09-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_dislikemodel_post_alter_likemodel_post_and_more'),
        ('authapp', '0007_customuser_about_me_customuser_github_and_more'),
    ]

    operations = [
    ]
