# Generated by Django 4.2.4 on 2023-09-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_profileuser_top_result_friendsrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendsrequest',
            unique_together={('sent_from', 'sent_to')},
        ),
        migrations.CreateModel(
            name='DuckHuntModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_result', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='duck_hunt', to='authapp.profileuser')),
            ],
        ),
    ]
