# Generated by Django 4.2.4 on 2023-09-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_friendsrequest_unique_together_duckhuntmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislikemodel',
            options={'verbose_name': 'Дизлай', 'verbose_name_plural': 'Дизлайки'},
        ),
        migrations.AlterModelOptions(
            name='duckhuntmodel',
            options={'verbose_name': 'Duck Hunt', 'verbose_name_plural': 'Duck Hunt'},
        ),
        migrations.AlterModelOptions(
            name='friendsrequest',
            options={'verbose_name': 'Друзья', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterModelOptions(
            name='likemodel',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='messagesmodel',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.CreateModel(
            name='SuperMarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_result', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='super_mario', to='authapp.profileuser')),
            ],
            options={
                'verbose_name': 'Super Mario',
                'verbose_name_plural': 'Super Mario',
            },
        ),
    ]
