# Generated by Django 4.2.4 on 2023-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_supermariomodel_options_kerbymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kerbymodel',
            options={'verbose_name': 'Kerby', 'verbose_name_plural': 'Kerby'},
        ),
        migrations.AlterModelOptions(
            name='supermariomodel',
            options={'verbose_name': 'Super Mario', 'verbose_name_plural': 'Super Mario'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Прошел активацтю'),
        ),
    ]
