# Generated by Django 4.2.4 on 2023-10-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_messages_app', '0002_alter_chat_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_message', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Личные сообщения',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.AddIndex(
            model_name='privatemessagesmodel',
            index=models.Index(fields=['sender', 'recipient'], name='sender_recipient_idx'),
        ),
    ]
