# Используйте официальный образ Nginx
FROM nginx:latest

# Копируйте свою конфигурацию Nginx в контейнер
COPY nginx.conf /etc/nginx/nginx.conf

# Опционально, скопируйте файлы для вашего веб-сайта (если они есть)
COPY /static /usr/share/nginx/html

# Экспонируйте порт 80
EXPOSE 80

# Запустите Nginx
CMD ["nginx", "-g", "daemon off;"]
